# Generated by Django 2.2.5 on 2021-08-24 16:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210730_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bm_approval',
            field=models.BooleanField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hq_approval',
            field=models.BooleanField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bm_approval',
            field=models.BooleanField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='hq_approval',
            field=models.BooleanField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
